### ISSUE TITLE
Drop shadows on the buttons have too much spread

### ISSUE THREAD

**Issue by Joshalosh** [loki-project/loki-ios-wallet#1]
The drop shadows on the buttons are pretty intense. The spread could probably decrease substantially as well as the distance.

![2019-06-04 22 25 18](https://user-images.githubusercontent.com/13159770/58878890-adb79d00-8717-11e9-868a-56b4ec43c645.jpg)
.

**Comment by Mikunj** [comment]
Removed all shadows.
