### ISSUE TITLE
Loki tokens not showing in ios Loki wallet

### ISSUE THREAD

**Issue by Menadian** [loki-project/loki-ios-wallet#24]
Hello, I transferred Loki tokens from KuCoin to my iOS Loki wallet, but my wallet shows a 0 balance even after synchronization completed. KuCoin indicates the transfer was completed several hours ago.  Please help.  Thank you

**Comment by flecill** [comment]
Hi, I have experienced similar issue, though it was Win GUI wallet.
Please check if it is latest version, and switch remote nodes for some times.
After recync, my balance is recovered properly.

**Comment by Menadian** [comment]
Thank you for responding.  I was able to load the GUI wallet on laptop and saw the tokens were received.  I restored the iOS wallet and it worked showing the tokens.
