### ISSUE TITLE
Language selection display bug

### ISSUE THREAD

**Issue by yidakee** [loki-project/loki-ios-wallet#7]
Iphone 5S - A1457 - iOS 12.0.1  (latest is 12.3.1, updating now and report)

Loki iOS wallet 1.0.0

![loki_lang_bug](https://user-images.githubusercontent.com/16577836/59192361-0eacfe00-8b7a-11e9-86e9-31810d4d6c3c.jpg)

Both Portuguese and Dutch should be able to fit, more than enough screen real estate

**Comment by Mikunj** [comment]
Should be fixed in the next build.
